#!/usr/bin/env python3
"""SRS traceability generator.

TRACE: REQ-VFY-007, REQ-DOC-002.

Walks the source tree, finds every `REQ-XXX-NNN` marker, and writes
`docs/SRS_TRACE.md` with two tables:

  * Forward  — requirement → file:line in the source tree
  * Backward — file:line in source tree → requirement

Also verifies that every `REQ-XXX-NNN` it sees is registered in
`docs/SRS.md`. Anything undeclared causes a non-zero exit.

The script is intentionally dependency-free (only Python 3.8+).
"""

from __future__ import annotations

import os
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRS_PATH = REPO_ROOT / "docs" / "SRS.md"
OUT_PATH = REPO_ROOT / "docs" / "SRS_TRACE.md"

# Skips — the same paths cargo/.gitignore ignores.
EXCLUDE_DIRS = {".git", "target", ".cargo-patches", "node_modules"}
SOURCE_EXTS = {
    ".rs", ".toml", ".md", ".sh", ".py", ".yaml", ".yml",
    ".json", ".xml", ".cfg", ".defaults", ".txt", ".c", ".h",
}

# REQ-<TAG>-NNN where TAG is at least 2 letters (so we don't match REQ-X).
REQ_PATTERN = re.compile(r"\b(REQ-[A-Z]+-\d{3})\b")
PR_PATTERN = re.compile(r"\bREQUIREMENT=(REQ-[A-Z]+-\d{3})\b")


def walk_sources() -> list[Path]:
    paths: list[Path] = []
    for root, dirs, files in os.walk(REPO_ROOT):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for f in files:
            if Path(f).suffix in SOURCE_EXTS:
                paths.append(Path(root) / f)
    return paths


def registered_requirements() -> set[str]:
    if not SRS_PATH.exists():
        raise SystemExit(f"missing {SRS_PATH}; cannot verify traceability")
    text = SRS_PATH.read_text(encoding="utf-8")
    return {m.group(1) for m in REQ_PATTERN.finditer(text)}


def main() -> int:
    registered = registered_requirements()
    forward: dict[str, list[tuple[str, int]]] = defaultdict(list)
    backward: list[tuple[str, int, str]] = []
    unknown: set[str] = set()

    for path in walk_sources():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for lineno, line in enumerate(text.splitlines(), 1):
            for m in REQ_PATTERN.finditer(line):
                req = m.group(1)
                rel = path.relative_to(REPO_ROOT)
                forward[req].append((str(rel), lineno))
                backward.append((str(rel), lineno, req))
                if req not in registered:
                    unknown.add(req)

    # Emit the report.
    lines = [
        "# SRS Traceability Matrix",
        "",
        "TRACE: REQ-VFY-007. Auto-generated by `tools/ci/srs_trace.py`. Do not",
        "edit by hand — the script regenerates this file on every CI run.",
        "",
        "## Forward map (requirement → implementation sites)",
        "",
        "| Requirement | Sites |",
        "|---|---|",
    ]
    for req in sorted(registered):
        sites = forward.get(req, [])
        if not sites:
            lines.append(f"| {req} | _(no implementation references yet — FAIL)_ |")
        else:
            rendered = "<br>".join(f"`{f}:{ln}`" for f, ln in sites)
            lines.append(f"| {req} | {rendered} |")

    lines.extend([
        "",
        "## Backward map (implementation site → requirement)",
        "",
        "| Site | Requirement |",
        "|---|---|",
    ])
    for f, ln, req in sorted(backward):
        lines.append(f"| `{f}:{ln}` | {req} |")

    lines.append("")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")

    # Sanity report.
    print(f"registered requirements: {len(registered)}")
    print(f"implementation references: {len(backward)}")
    if unknown:
        print(f"FAIL: {len(unknown)} requirement markers are not registered in SRS.md:")
        for req in sorted(unknown):
            print(f"  - {req}")
        return 1
    print("OK: all referenced requirements are declared in SRS.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
